### PR TITLE
global: missing imports, tests fixes and more

### PR DESCRIPTION
**Pull request by jalavik**
Fixes import dependencies on refextract. Fixes tests and improves documentation structure.

### CODE REVIEW

**Comment by jalavik** [comment]
Added PEP8 fixes now. `python setup.py test` should be all green now.

**Comment by jalavik** [comment]
Hmm. Lookups to `invenio.base.globals:cfg` are not playing nicely. Maybe it's because it's missing `invenio_classifier` package in the `PACKAGES`?

**Comment by jirikuncar** [comment]
@jalavik probably. One should set `PACKAGES`  for each testsuite (e.g. `tests/helpers.py:ClassifierTest.config`).

**Comment by jalavik** [comment]
:+1:

**Pull request merged**
